### ISSUE TITLE
Possible to Use with Multiple Accounts

### ISSUE THREAD

**Issue by bevanjkay** [alfredapp/google-drive-workflow#1]
Hi @vitorgalvao, thanks for putting this together, as Alfred not indexing Google Drive has been driving me insane. In my case, I am logged into two Google accounts, so there are two `google_drive_path` locations. Would it be possible to provide two paths? Or should I try to run a second instance of the workflow with modified keywords?

**Comment by vitorgalvao** [comment]
Were you in the the Alfred forum thread and I missed it? I made no announcement about this repository yet and you’ve found it!

[Published a new release with support for multiple paths](https://github.com/vitorgalvao/alfred-google-drive/releases/tag/2021.2).

**Comment by bevanjkay** [comment]
@vitorgalvao No I'm not, saw you released a new script through Homebrew and stumbled across this in the process 👍🏻

What's the best way to support your work?

**Comment by vitorgalvao** [comment]
> What's the best way to support your work?

Thank you for asking. [PayPal](https://www.paypal.me/vitorgalvao), I guess.
