### ISSUE TITLE
Search Google "Shared drives"

### ISSUE THREAD

**Issue by Adamrec** [alfredapp/google-drive-workflow#10]
I've done the standard set up and the GD search is finding everything in "My Drive" but I am not seeing results for "Shared drives"

**Comment by vitorgalvao** [comment]
Please don’t skip the template. And please read [the instructions](https://github.com/alfredapp/google-drive-workflow#instructions):

> `google_drive_path`: The location of Google Drive on your file system. Can take multiple paths separated by commas.

**Comment by Adamrec** [comment]
Can you help me with where "google_drive_path" is? Or where to manipulate it?

**Comment by vitorgalvao** [comment]
That’s also in the instructions. It’s a [Workflow Environment Variable](https://www.alfredapp.com/help/workflows/advanced/variables/#environment).

**Comment by Adamrec** [comment]
Thank you!
