### ISSUE TITLE
Not sure where and how to set the Workflow Environment Variables

### ISSUE THREAD

**Issue by amauryhubault** [alfredapp/google-drive-workflow#14]
Hi,

First I'd like to thank you because I've been looking for a workflow like yours for several months. Can't wait to set it up properly.
I may ask beginner questions, apologies, but I already searched in existing open and closed issues without success.

About your mention "The Workflow Environment Variables have defaults which will work for most. You only have to mess with them if you have an atypical setup.

    google_drive_path: The location of Google Drive on your file system. Can take multiple paths separated by commas."
    
 I don't know exactly where I'm suppose to edit them? I think I'm having an atypical setup, with 2 Google drive accounts, one with Shared drive. When trying to use the basic settings and following the cache building instructions, no file is being found.

Thanks a lot for your help.

**Comment by vitorgalvao** [comment]
[Documentation with screenshot](https://www.alfredapp.com/help/workflows/advanced/variables/#environment).
