### ISSUE TITLE
tmp.db does not exist but this error persists in any command `ERROR: Google Drive[Run Script] Cache creation already in progress`

### ISSUE THREAD

**Issue by mac137** [alfredapp/google-drive-workflow#17]
### Diagnostic

```markdown
2022.2

### Alfred version
4.6.1

### macOS version
12.1

### Workflow environment variables
Dict {
    ignore_list = /Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/21_pointpix_data,/Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/22_other_datasets,/Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/51_BIM2TWIN_data
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive-101371721066474237144
}

### Google drive paths
Exists: ~/Library
27G
206166 paths
Exists: ~/Desktop
8.0K
3 paths

### Cache dir

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed
' to Post Notification
[00:50:25.456] Google Drive[Post Notification] Processing complete
[00:50:25.457] Google Drive[Post Notification] Passing output '### Workflow version
2022.2

### Alfred version
4.6.1

### macOS version
12.1

### Workflow environment variables
Dict {
    ignore_list = /Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/21_pointpix_data,/Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/22_other_datasets,/Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/51_BIM2TWIN_data
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive-101371721066474237144
}

### Google drive paths
Exists: ~/Library
27G
206166 paths
Exists: ~/Desktop
8.0K
3 paths

### Cache dir

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed
' to Play Sound
```

### Debugger output

```codeblock
`[00:49:41.048] ERROR: Google Drive[Run Script] Cache creation already in progress`
```

### More details

When I do
`ls "${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive"`
there is no file there.

I tried reinstalling this package and the same problem occurs: 
`[00:55:35.368] ERROR: Google Drive[Run Script] Cache creation already in progress`
and there is no file in `${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive`

I tried also these methods from #15
`osascript -e 'tell application id "com.runningwithcrayons.Alfred" to run trigger "googledrivelaunchd" in workflow "com.alfredapp.googledrive" with argument "uninstall"'
osascript -e 'tell application id "com.runningwithcrayons.Alfred" to run trigger "googledrivelaunchd" in workflow "com.alfredapp.googledrive" with argument "install"'`
 and the same problem occurs:
```00:57:36.031] Google Drive[External] Processing complete
[00:57:36.059] Google Drive[External] Passing output 'uninstall' to Run Script
[00:57:36.107] Google Drive[Run Script] Processing complete
[00:57:36.125] Google Drive[Run Script] Passing output '' to Conditional
[00:57:42.552] Google Drive[External] Processing complete
[00:57:42.583] Google Drive[External] Passing output 'install' to Run Script
[00:57:42.629] Google Drive[Run Script] Processing complete
[00:57:42.642] Google Drive[Run Script] Passing output 'BUILD_CACHE' to Conditional
[00:57:42.642] Google Drive[Conditional] Processing complete
[00:57:42.642] Google Drive[Conditional] Passing output 'BUILD_CACHE' to Run Script
[00:57:42.725] Google Drive[External] Processing complete
[00:57:42.729] Google Drive[External] Passing output '' to Arg and Vars
[00:57:42.730] Google Drive[Arg and Vars] Processing complete
[00:57:42.731] Google Drive[Arg and Vars] Passing output '' to Run Script
[00:57:42.808] ERROR: Google Drive[Run Script] Cache creation already in progress
[00:57:42.817] Google Drive[Run Script] Processing complete
[00:57:42.818] Google Drive[Run Script] Passing output 'ONGOING_REBUILD' to Run Script
[00:57:42.819] Google Drive[Run Script] Passing output 'ONGOING_REBUILD' to Conditional
[00:57:42.819] Google Drive[Conditional] Processing complete
[00:57:42.820] Google Drive[Conditional] Passing output 'ONGOING_REBUILD' to Post Notification
[00:57:42.821] Google Drive[Post Notification] Processing complete
[00:57:42.821] Google Drive[Post Notification] Passing output 'ONGOING_REBUILD' to Play Sound
[00:57:43.339] Google Drive[Run Script] Processing complete
[00:57:43.354] Google Drive[Run Script] Passing output '' to Run Script
[00:57:43.356] Google Drive[Run Script] Passing output '' to Conditional
[00:57:43.357] Google Drive[Conditional] Processing complete
[00:57:43.357] Google Drive[Conditional] Passing output '' to Conditional
```
and no file in `${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive`

Any idea how to fix this problem?

**Comment by vitorgalvao** [comment]
Try the new version. Also, please take care when pasting the diagnostics data. What you've pasted is jumbled and missing parts. Don’t edit it, just paste once.

**Comment by mac137** [comment]
I tried the version 2022.4 and exactly the same problem occurs.

**Comment by vitorgalvao** [comment]
That seems unlikely. You didn't even have time for the cache to build. Run the diagnostics again, and this time please take care with the pasting of information.

**Comment by mac137** [comment]
I tried to run `!gddiagnostic' with version 2022.4 and it does not display anything in the debug console:
```bash
[02:01:05.420] Google Drive[Keyword] Processing complete
[02:01:05.421] Google Drive[Keyword] Passing output '' to Run Script
```

When I run either of the commands `:gdlaunchd`, `:gdrebuildcache`, I get the same error all the time:
`[02:05:35.512] ERROR: Google Drive[Run Script] Cache creation already in progress`.

In `Activitiy Monitor`, process `com.runningwithcrayons.Alfred` does not exist.
Also:
```
ls -l "${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive"
total 0
```

😕

**Comment by mac137** [comment]
Update: `!gddiagnostic' worked after a couple of minutes.
```
[02:10:15.897] Google Drive[Post Notification] Processing complete
[02:10:15.898] Google Drive[Post Notification] Passing output '### Workflow version
2022.4

### Alfred version
4.6.1

### macOS version
12.1

### Workflow environment variables
Dict {
    ignore_list = /Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/21_pointpix_data,/Volumes/GoogleDrive-101371721066474237144/My Drive/Cambridge/22_other_datasets
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive-101371721066474237144
}

### Google drive paths
Exists: /Volumes/GoogleDrive-101371721066474237144
169M
275884 paths

### Cache dir
Files NOT present

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed
' to Play Sound
```

**Comment by vitorgalvao** [comment]
> In Activitiy Monitor, process `com.runningwithcrayons.Alfred` does not exist.

I have no idea why you’re checking this. It is not relevant.

> I tried to run `!gddiagnostic' with version 2022.4 and it does not display anything in the debug console

The debugger has nothing to do with it. Again, **please follow the instructions**. It tells you to run the command *and wait* to paste it. It’s not about the debugger.

> When I run either of the commands `:gdlaunchd`, `:gdrebuildcache`, I get the same error all the time

I’m at a loss as to how else ask you to be patient. You are running both and making them try to trample over each other. You’re not supposed to run everything at once, you’re supposed to run one of them and wait. From the first post of the fist issue you’ve been trying to do everything at once. It is impossible to help you like that.

You’re a PhD student in an informatics field. Following documentation and instructions are must-have skills to be any good at it.

Your `ignore_list` is wrong; you’re not supposed to add full paths to it. That is also explained in the instructions.

At this point, you should reboot your machine **and wait**. That’s it, just restart **and be patient** while the cache builds.

If you keep shooting all over the place without reading, it will not be possible to proceed.

**Comment by mac137** [comment]
Many thanks for your reply! I literally waited 24 hours and still, it says
```
[23:39:11.458] ERROR: Google Drive[Run Script] Cache creation already in progress
```

Also:
```
ls -l "${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive"                                 
total 0
```

and `!gddiagnostic`:
```
### Workflow version
2022.4

### Alfred version
4.6.1

### macOS version
12.1

### Workflow environment variables
Dict {
    ignore_list = 21_pointpix_data,22_other_datasets
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive-101371721066474237144
}

### Google drive paths
Exists: /Volumes/GoogleDrive-101371721066474237144
169M
275892 paths

### Cache dir
Files NOT present

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	1	com.alfredapp.launchd.googledrivecache
Installed
' to Play Sound
```

It looks very similar to #15. Is there any way to fully (hard) reset this workflow? I tried reinstalling it and it did not help. Please help.

**Comment by vitorgalvao** [comment]
> It looks very similar to #15.

It’s not.

> Is there any way to fully (hard) reset this workflow?

It’s [the AppleScript commands](https://github.com/alfredapp/google-drive-workflow/issues/15#issuecomment-1013863613). But delete the cache directory first. Made you’ve changed the permissions.

There’s something fundamentally wrong with your setup that only you are experiencing.

What’s the result of `ps A | grep Alfred`?

**Comment by mac137** [comment]
I have just given up on this workflow and installed Dropbox instead. Thanks for your help anyway!

**Comment by vitorgalvao** [comment]
Run `osascript -e 'tell application id "com.runningwithcrayons.Alfred" to run trigger "googledrivelaunchd" in workflow "com.alfredapp.googledrive" with argument "uninstall"'` anyway, so it doesn’t try to keep rebuilding.
