### ISSUE TITLE
Cache build worked however no files or folders I'm storing offline are shown in the search

### ISSUE THREAD

**Issue by apotenza92** [alfredapp/google-drive-workflow#2]

**Comment by vitorgalvao** [comment]
Do you have a forum account? The conversation would be better had [there](https://www.alfredforum.com/topic/17318-google-drive-—-list-file-stream-contents-from-google-drive/). I’ll need the information asked about on [the second post](https://www.alfredforum.com/topic/17318-google-drive-—-list-file-stream-contents-from-google-drive/#comment-89267).

I’ll also need as much information as you can give me about your setup. I don’t use Google Drive and no one else is experiencing this, so I need clues.

**Comment by vitorgalvao** [comment]
Closing for lack of reply.
