### ISSUE TITLE
Index is not being created

### ISSUE THREAD

**Issue by alxsimo** [alfredapp/google-drive-workflow#20]
### Workflow version
2022.4

### Alfred version
4.6.1

### macOS version
12.0.1

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive/My Drive
}

### Google drive paths
Exists: /Volumes/GoogleDrive/My Drive
22M
11314 paths

### Cache dir
Files NOT present

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed

### Debugger output

```codeblock
[13:40:37.583] Google Drive[Keyword] Processing complete
[13:40:37.588] Google Drive[Keyword] Passing output '' to Run Script
*[13:40:37.819] ERROR: Google Drive[Run Script] Cache creation already in progress*
[13:40:37.822] Google Drive[Run Script] Processing complete
[13:40:37.823] Google Drive[Run Script] Passing output 'ONGOING_REBUILD' to Run Script
[13:40:37.825] Google Drive[Run Script] Passing output 'ONGOING_REBUILD' to Conditional
[13:40:37.828] Google Drive[Conditional] Processing complete
[13:40:37.828] Google Drive[Conditional] Passing output 'ONGOING_REBUILD' to Post Notification
[13:40:37.829] Google Drive[Post Notification] Processing complete
[13:40:37.830] Google Drive[Post Notification] Passing output 'ONGOING_REBUILD' to Play Sound
```

### More details

It always says `Cache creation already in progress` but never gets generated.

I waited even days, and still not. Every time, trying to generate the index, says it's still on progress.

Please request any needed info or tell how to help :)

**Comment by vitorgalvao** [comment]
Does running `gd` show that a cache rebuilding is in progress, or that no cache was found?

[In a Terminal](https://support.apple.com/en-gb/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac), what’s the output of `ps A | grep Alfred`?

**Comment by alxsimo** [comment]
@vitorgalvao thanks for your answer

![image](https://user-images.githubusercontent.com/579465/150137260-e3f23511-9ead-4baf-b165-5b6c3e51f2ee.png)

ps output: 

```
➜  ~ ps A | grep Alfred
  593   ??  S      0:26.78 /Applications/Alfred 4.app/Contents/MacOS/Alfred
 6146   ??  S      0:26.25 /Applications/Alfred 4.app/Contents/Preferences/Alfred Preferences.app/Contents/MacOS/Alfred Preferences
 7023 s000  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox Alfred
```

**Comment by vitorgalvao** [comment]
Thank you for the details. Bug found and squashed in `2022.5`.

**Comment by alxsimo** [comment]
@vitorgalvao updated to 2022.5 and works perfectly

kudos!
