### ISSUE TITLE
Possible to search in MyDrive and in SharedDrive at the same time ?

### ISSUE THREAD

**Issue by MiraDavid** [alfredapp/google-drive-workflow#23]
### Workflow version
2022.5

### Alfred version
4.6.1

### macOS version
12.0.1

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive/Mon Drive
}

### Google drive paths
Exists: /Volumes/GoogleDrive/Mon Drive
40M
22873 paths

### Cache dir
cache.db

### Cache file
16777220 97426838 -rw-r--r-- 1 david staff 0 3899392 "Jan 20 10:54:03 2022" "Jan 20 10:51:36 2022" "Jan 20 10:51:36 2022" "Jan 20 10:49:41 2022" 4096 8200 0 /Users/david/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed

### Debugger output

```codeblock
No bug - just a question
```

### More details

The workflow works perfectly to search files into "MyDrive" folder. I also have "Shared Drive" on my computer.
Is ot possible with the workflow to search into MyDrive and in SharedDrive at the same time ?

**Comment by vitorgalvao** [comment]
It’s explained in the instructions. Edit the `google_drive_path` Workflow Environment Variable to add both paths, separated by commas.
