### ISSUE TITLE
Google shared drive

### ISSUE THREAD

**Issue by cultureghem** [alfredapp/google-drive-workflow#26]
Hi Victor,

thank you for your script, really helping me out using google drive with Alfred.
Is it possible to add shared drives to your workflow? Now I only get results for files in my personal drive but at the office we use shared drives and those files don't come up.

Thanks in advance,
Yannick

**Comment by vitorgalvao** [comment]
You need to change the `google_drive_path` environment variable, as per [the instructions](https://github.com/alfredapp/google-drive-workflow). Then rebuild with `:gdrebuildcache`.

Making it `/Volumes/GoogleDrive/` should be enough, but do note this will increase the time needed to generate the cache and its size.

**Comment by cultureghem** [comment]
Thank you very much!
kind regards,
Yannick
[image: Logo Cultureghem] <https://www.cultureghem.be>

  Yannick Roels
***@***.*** T.:  +32 (0)2 556 11 79
M.:  +32 (0)494 16 65 28 <+320494166528> Ropsy Chaudronstraat 24/48
B - 1070 Brussel <https://goo.gl/maps/H5BfQGXtnAB2> [image: Campagnebeeld]
<https://cultureghem.be/2021/01/01/dreamkitchen/>
