### ISSUE TITLE
No cache found (with 2 Google Drive accounts syncing)

### ISSUE THREAD

**Issue by thiemehennis** [alfredapp/google-drive-workflow#27]
### Workflow version
2022.6

### Alfred version
4.6.2

### macOS version
10.13.6

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive/My Drive
}

### Google drive paths
Exists: /Volumes/GoogleDrive/My Drive
35G	/Volumes/GoogleDrive/MyDrive
16272 paths

### Cache dir
Files NOT present

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed

### Debugger output

```codeblock
[11:26:32.803] Logging Started...
[11:26:40.105] Google Drive[Script Filter] Queuing argument 'C'
[11:26:40.231] Google Drive[Script Filter] Queuing argument 'CL'
[11:26:40.397] Google Drive[Script Filter] Queuing argument 'CLT'
[11:26:40.800] Google Drive[Script Filter] Script with argv 'CLT' finished
[11:26:40.807] Google Drive[Script Filter] {"items":[{"title":"No cache found!","subtitle":"Run either :gdlaunchd or :gdrebuildcache. Consult the “About this Workflow” section.","valid":false}]}
```

### More details

I don't get any results. I have two Google accounts syncing with the new Google Drive client. My setting is on Streaming files (not mirroring). I have many files named CLT so at least some should pop up. Not sure if it's relevant, but my /Users/Mac/Library/Caches folder is not indexed with Spotlight (I added that folder to the Privacy tab in Spotlight long time ago).

**Comment by vitorgalvao** [comment]
> I don't get any results.

Because there’s no cache, though it’s unclear why. Run `:gdrebuildcache` now and try searching again in about an hour (it won’t take that long; I’m giving it an insane margin) or after you get a notification. Keep the debugger open before you do it, to look for any errors.

> Not sure if it's relevant, but my /Users/Mac/Library/Caches folder is not indexed with Spotlight

It’s not, but thank you for mentioning it. Extra details do help with debugging.

**Comment by thiemehennis** [comment]
First, I don't need this workflow anymore, because I found out that Alfred wasn't indexing certain folders because they were beyond the Scope (which can be set in the prefs).

But I did the rebuilt action, and this is what came out of the debugger:

> [09:01:23.592] Logging Started...
> [09:01:35.349] Logging Stopped.
> [09:01:35.893] Logging Started...
> [09:01:38.900] Google Drive[Keyword] Processing complete
> [09:01:38.933] Google Drive[Keyword] Passing output '' to Run Script
> [09:01:39.252] ERROR: Google Drive[Run Script] /Volumes/GoogleDrive/My Drive/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.475F9123-3117-4A54-A243-D66E964A83B7/rebuild_cache:27:in `start_with?': no implicit conversion of Regexp into String (TypeError)
> 	from /Volumes/GoogleDrive/My Drive/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.475F9123-3117-4A54-A243-D66E964A83B7/rebuild_cache:27:in `block in <main>'
> 	from /Volumes/GoogleDrive/My Drive/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.475F9123-3117-4A54-A243-D66E964A83B7/rebuild_cache:27:in `reject'
> 	from /Volumes/GoogleDrive/My Drive/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.475F9123-3117-4A54-A243-D66E964A83B7/rebuild_cache:27:in `<main>'
> [09:01:39.268] Google Drive[Run Script] Processing complete
> [09:01:39.269] Google Drive[Run Script] Passing output '' to Run Script
> [09:01:39.270] Google Drive[Run Script] Passing output '' to Conditional
> [09:01:39.271] Google Drive[Conditional] Processing complete
> [09:01:39.272] Google Drive[Conditional] Passing output '' to Conditional
> [09:01:39.274] Google Drive[Conditional] Processing complete
> [09:01:39.275] Google Drive[Conditional] Passing output '' to Post Notification

**Comment by vitorgalvao** [comment]
Ah, the problem is that you’re on a too old macOS version.

> I don't need this workflow anymore

Do run `:gdlaunchd` to remove the periodic cache building (which would fail without the Workflow so it’s not a big deal or something to worry about anyway).

**Comment by thiemehennis** [comment]
Thanks!

Op wo 2 feb. 2022 12:44 schreef Vítor Galvão ***@***.***>:
