### ISSUE TITLE
Daily Kernel Panics, probably caused by the indexing of Shared Drives

### ISSUE THREAD

**Issue by Ste-SR** [alfredapp/google-drive-workflow#28]
Hello,
when this plugin indexes Shared Drives, after some time the computer crashes with a Kernel Panic (I've pasted the problem report below).

The device is a MBP 14" 16GB M1 Pro with the latest version of Mac Os, Google Drive, Alfred. It's been happening for the past months, but since the indexing of Shared Drives wasn't default but something I had to manually set, I just gave up on having it. With the previous versions of the plugin, when I would try adding the Shared Drives folder in the preferences and force the re-index, the Mac would crash like clockwork after a little while. Now that it has become a default setting for this plugin, I fear this may result in many confused users finding out every morning that their Mac has crashed overnight.

I don't know if the issue is caused by the plugin itself, by GDrive or by MacOS, I just hope to contribute all the info I can to help trace the main cause of the issue.

Mac Os Problem Report after reboot

    panic(cpu 1 caller 0xfffffe00125c5594): zone map exhaustion: waited for 5050ms (pages: 375409, max: 375410, wanted: 2) @zalloc.c:4623
    Debugger message: panic
    Memory ID: 0x1
    OS release type: User
    OS version: 21D62
    Kernel version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Fileset Kernelcache UUID: FA4EB485BA9DC1EBAA5D0E80232A48CC
    Kernel UUID: BADF56F4-2876-3FF4-AC12-F25E78B09AA1
    iBoot version: iBoot-7429.81.3
    secure boot?: YES
    Paniclog version: 13
    KernelCache slide: 0x000000000abec000
    KernelCache base:  0xfffffe0011bf0000
    Kernel slide:      0x000000000b420000
    Kernel text base:  0xfffffe0012424000
    Kernel text exec slide: 0x000000000b508000
    Kernel text exec base:  0xfffffe001250c000
    mach_absolute_time: 0x1dca67695be
    Epoch Time:        sec       usec
      Boot    : 0x62153aec 0x0002d978
      Sleep   : 0x621681f1 0x0006714a
      Wake    : 0x621681f1 0x00092e45
      Calendar: 0x62168842 0x000ddaab
    
    Zone info:
    Foreign   : 0xfffffe0019b94000 - 0xfffffe0019ba8000
    Native    : 0xfffffe1000628000 - 0xfffffe3000628000
    Readonly  : 0xfffffe14cd2f4000 - 0xfffffe1666c88000
    Metadata  : 0xfffffe8919330000 - 0xfffffe89252cc000
    Bitmaps   : 0xfffffe89252cc000 - 0xfffffe892ae74000
    Largest zones:
    Zone Name                      Cur Size  Free Size
    kext.   kalloc.32768              5215M         0K
            APFS_4K_OBJS               152M         0K
            APFS_INODES                 71M     36467K
            ubc_info zone               17M       224K
            APFS_BTREE_NODES            10M         9K
    CORE 0 PVH locks held: None
    CORE 1 PVH locks held: None
    CORE 2 PVH locks held: None
    CORE 3 PVH locks held: None
    CORE 4 PVH locks held: None
    CORE 5 PVH locks held: None
    CORE 6 PVH locks held: None
    CORE 7 PVH locks held: None
    CORE 0: PC=0xfffffe001266d990, LR=0xfffffe001266d860, FP=0xfffffe7023dfbbe0
    CORE 1 is the one that panicked. Check the full backtrace for details.
    CORE 2: PC=0xfffffe0012592f4c, LR=0xfffffe0012592f4c, FP=0xfffffe7023d1bef0
    CORE 3: PC=0xfffffe0012592f50, LR=0xfffffe0012592f4c, FP=0xfffffe7023dcbef0
    CORE 4: PC=0xfffffe0012592f50, LR=0xfffffe0012592f4c, FP=0xfffffe7023a9bef0
    CORE 5: PC=0xfffffe0012592f50, LR=0xfffffe0012592f4c, FP=0xfffffe7023c9bef0
    CORE 6: PC=0xfffffe0012592f4c, LR=0xfffffe0012592f4c, FP=0xfffffe7023ddbef0
    CORE 7: PC=0xfffffe0012592f4c, LR=0xfffffe0012592f4c, FP=0xfffffe7021c5bef0
    Panicked task 0xfffffe24cd214678: 4324 pages, 22 threads: pid 360: WindowServer
    Panicked thread: 0xfffffe1667ec4100, backtrace: 0xfffffe70237eb110, tid: 177086
		      lr: 0xfffffe001255e4e8  fp: 0xfffffe70237eb180
		      lr: 0xfffffe001255e1b8  fp: 0xfffffe70237eb1f0
		      lr: 0xfffffe001269e2bc  fp: 0xfffffe70237eb210
		      lr: 0xfffffe00126906c8  fp: 0xfffffe70237eb290
		      lr: 0xfffffe001268e118  fp: 0xfffffe70237eb350
		      lr: 0xfffffe00125137f8  fp: 0xfffffe70237eb360
		      lr: 0xfffffe001255de2c  fp: 0xfffffe70237eb700
		      lr: 0xfffffe001255de2c  fp: 0xfffffe70237eb770
		      lr: 0xfffffe0012d71738  fp: 0xfffffe70237eb790
		      lr: 0xfffffe00125c5594  fp: 0xfffffe70237eb860
		      lr: 0xfffffe00125c4a08  fp: 0xfffffe70237eba00
		      lr: 0xfffffe00125c7158  fp: 0xfffffe70237eba50
		      lr: 0xfffffe001256f690  fp: 0xfffffe70237eba90
		      lr: 0xfffffe001261e70c  fp: 0xfffffe70237ebb80
		      lr: 0xfffffe001253cd30  fp: 0xfffffe70237ebcf0
		      lr: 0xfffffe0012553144  fp: 0xfffffe70237ebd80
		      lr: 0xfffffe00126836a8  fp: 0xfffffe70237ebe50
		      lr: 0xfffffe001268e550  fp: 0xfffffe70237ebf10
		      lr: 0xfffffe00125137f8  fp: 0xfffffe70237ebf20
    
    last started kext at 1154273237215: com.apple.filesystems.smbfs	4.0 (addr 0xfffffe0012408c70, size 64483)
    loaded kexts:
    com.apple.filesystems.smbfs	4.0
    com.apple.filesystems.autofs	3.0
    com.apple.fileutil	20.036.15
    com.apple.driver.AppleTopCaseHIDEventDriver	5020.1
    com.apple.driver.AppleBiometricServices	1
    com.apple.driver.CoreKDL	1
    com.apple.driver.usb.AppleUSBHostBillboardDevice	1.0
    com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
    com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
    com.apple.driver.DiskImages.RAMBackingStore	493.0.0
    com.apple.driver.DiskImages.FileBackingStore	493.0.0
    com.apple.filesystems.apfs	1933.80.3
    com.apple.driver.SEPHibernation	1
    com.apple.driver.BCMWLANFirmware4387.Hashstore	1
    com.apple.driver.AppleUSBDeviceNCM	5.0.0
    com.apple.driver.AppleThunderboltIP	4.0.3
    com.apple.driver.AppleFileSystemDriver	3.0.1
    com.apple.nke.l2tp	1.9
    com.apple.filesystems.tmpfs	1
    com.apple.filesystems.lifs	1
    com.apple.IOTextEncryptionFamily	1.0.0
    com.apple.filesystems.hfs.kext	582.60.2
    com.apple.security.BootPolicy	1
    com.apple.BootCache	40
    com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
    com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
    com.apple.driver.ApplePMP	1
    com.apple.driver.AppleCS42L84Audio	530.2
    com.apple.driver.AppleSmartIO2	1
    com.apple.AppleEmbeddedSimpleSPINORFlasher	1
    com.apple.driver.AppleSN012776Amp	530.2
    com.apple.driver.AppleT6000SOCTuner	1
    com.apple.driver.AppleT6000CLPCv3	1
    com.apple.driver.AppleSmartBatteryManager	161.0.0
    com.apple.driver.AppleALSColorSensor	1.0.0d1
    com.apple.driver.AppleAOPVoiceTrigger	100.1
    com.apple.driver.ApplePMPFirmware	1
    com.apple.driver.AppleM68Buttons	1.0.0d1
    com.apple.driver.AppleProResHW	128.2.0
    com.apple.driver.AppleJPEGDriver	4.7.9
    com.apple.driver.AppleAVE2	530.3.0
    com.apple.driver.AppleAVD	555
    com.apple.AGXG13X	188.10
    com.apple.driver.AppleSDXC	3.1.1
    com.apple.driver.AppleSamsungSerial	1.0.0d1
    com.apple.driver.AppleSerialShim	1
    com.apple.driver.AppleMobileDispT600X-DCP	140.0
    com.apple.driver.AppleSPMIPMU	1.0.1
    com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
    com.apple.driver.AppleMCDP29XXUpdateSupport	1
    com.apple.driver.AppleDPDisplayTCON	1
    com.apple.driver.AppleEventLogHandler	1
    com.apple.driver.AppleS5L8960XNCO	1
    com.apple.driver.AppleT6000PMGR	1
    com.apple.driver.AppleS8000AES	1
    com.apple.driver.AppleS8000DWI	1.0.0d1
    com.apple.driver.AppleInterruptControllerV2	1.0.0d1
    com.apple.driver.AppleT8110DART	1
    com.apple.driver.AppleBluetoothModule	1
    com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
    com.apple.driver.AppleS5L8920XPWM	1.0.0d1
    com.apple.driver.AudioDMAController-T600x	100.51
    com.apple.driver.AppleT6000DART	1
    com.apple.driver.AppleSPIMC	1
    com.apple.driver.AppleS5L8940XI2C	1.0.0d2
    com.apple.driver.AppleT6000	1
    com.apple.iokit.IOUserEthernet	1.0.1
    com.apple.driver.usb.AppleUSBUserHCI	1
    com.apple.iokit.IOKitRegistryCompatibility	1
    com.apple.iokit.EndpointSecurity	1
    com.apple.driver.AppleDiskImages2	126.60.3
    com.apple.AppleSystemPolicy	2.0.0
    com.apple.nke.applicationfirewall	402
    com.apple.kec.InvalidateHmac	1
    com.apple.kec.AppleEncryptedArchive	1
    com.apple.driver.driverkit.serial	6.0.0
    com.apple.kext.triggers	1.0
    com.apple.iokit.IOAVBFamily	1010.2
    com.apple.plugin.IOgPTPPlugin	1000.11
    com.apple.iokit.IOEthernetAVBController	1.1.0
    com.apple.driver.AppleActuatorDriver	5430.21
    com.apple.driver.AppleHIDKeyboard	228
    com.apple.driver.AppleMultitouchDriver	5430.21
    com.apple.driver.AppleHSBluetoothDriver	5020.1
    com.apple.driver.IOBluetoothHIDDriver	9.0.0
    com.apple.driver.AppleMesaSEPDriver	100.99
    com.apple.iokit.IOBiometricFamily	1
    com.apple.driver.DiskImages.KernelBacked	493.0.0
    com.apple.driver.AppleXsanScheme	3
    com.apple.driver.AppleSEPHDCPManager	1.0.1
    com.apple.driver.AppleTrustedAccessory	1
    com.apple.iokit.AppleSEPGenericTransfer	1
    com.apple.driver.usb.networking	5.0.0
    com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
    com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
    com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
    com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
    com.apple.nke.ppp	1.9
    com.apple.driver.AppleBSDKextStarter	3
    com.apple.filesystems.hfs.encodings.kext	1
    com.apple.driver.AppleBTM	1.0.1
    com.apple.driver.AppleHIDTransportSPI	5400.30
    com.apple.driver.AppleHIDTransport	5400.30
    com.apple.driver.AppleInputDeviceSupport	5400.30
    com.apple.driver.AppleConvergedIPCOLYBTControl	1
    com.apple.driver.AppleConvergedPCI	1
    com.apple.driver.AppleBluetoothDebug	1
    com.apple.driver.AppleDCPDPTXProxy	1.0.0
    com.apple.driver.DCPDPFamilyProxy	1
    com.apple.driver.AppleCSEmbeddedAudio	530.2
    com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
    com.apple.driver.ApplePassthroughPPM	3.0
    com.apple.driver.AppleAOPAudio	102.2
    com.apple.driver.AppleEmbeddedAudio	530.2
    com.apple.iokit.AppleARMIISAudio	100.1
    com.apple.driver.AppleSPU	1
    com.apple.AGXFirmwareKextG13XRTBuddy	188.10
    com.apple.AGXFirmwareKextRTBuddy64	188.10
    com.apple.driver.DCPAVFamilyProxy	1
    com.apple.iokit.IOGPUFamily	35.11
    com.apple.iokit.IONVMeFamily	2.1.0
    com.apple.driver.AppleNANDConfigAccess	1.0.0
    com.apple.driver.AppleStockholmControl	1.0.0
    com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
    com.apple.driver.AppleDCP	1
    com.apple.driver.AppleFirmwareKit	1
    com.apple.iokit.IOMobileGraphicsFamily	343.0.0
    com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
    com.apple.driver.AppleDialogPMU	1.0.1
    com.apple.driver.AppleSPMI	1.0.1
    com.apple.driver.AppleUSBXDCIARM	1.0
    com.apple.driver.AppleUSBXDCI	1.0
    com.apple.iokit.IOUSBDeviceFamily	2.0.0
    com.apple.driver.usb.AppleSynopsysUSBXHCI	1
    com.apple.driver.usb.AppleUSBXHCI	1.2
    com.apple.driver.AppleEmbeddedUSBHost	1
    com.apple.driver.usb.AppleUSBHub	1.2
    com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
    com.apple.driver.AppleT6000TypeCPhy	1
    com.apple.driver.AppleT8103TypeCPhy	1
    com.apple.driver.AppleHPM	3.4.4
    com.apple.driver.AppleSART	1
    com.apple.driver.ApplePMGR	1
    com.apple.driver.AppleARMWatchdogTimer	1
    com.apple.driver.AppleDisplayCrossbar	1.0.0
    com.apple.iokit.IODisplayPortFamily	1.0.0
    com.apple.driver.AppleTypeCPhy	1
    com.apple.driver.AppleThunderboltNHI	7.2.8
    com.apple.driver.AppleT6000PCIeC	1
    com.apple.iokit.IOThunderboltFamily	9.3.3
    com.apple.driver.ApplePIODMA	1
    com.apple.driver.AppleT600xPCIe	1
    com.apple.driver.AppleMultiFunctionManager	1
    com.apple.driver.AppleBluetoothDebugService	1
    com.apple.driver.AppleBCMWLANCore	1.0.0
    com.apple.iokit.IO80211Family	1200.12.2b1
    com.apple.driver.IOImageLoader	1.0.0
    com.apple.driver.AppleOLYHAL	1
    com.apple.driver.corecapture	1.0.4
    com.apple.driver.AppleEmbeddedPCIE	1
    com.apple.driver.AppleMCA2-T600x	600.95
    com.apple.driver.AppleEmbeddedAudioLibs	100.9.1
    com.apple.driver.AppleFirmwareUpdateKext	1
    com.apple.driver.AppleH13CameraInterface	4.87.0
    com.apple.driver.AppleH10PearlCameraInterface	17.0.3
    com.apple.driver.AppleGPIOICController	1.0.2
    com.apple.driver.AppleFireStormErrorHandler	1
    com.apple.driver.AppleMobileApNonce	1
    com.apple.iokit.IOTimeSyncFamily	1000.11
    com.apple.driver.DiskImages	493.0.0
    com.apple.iokit.IOGraphicsFamily	593
    com.apple.iokit.IOBluetoothSerialManager	9.0.0
    com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
    com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
    com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
    com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
    com.apple.iokit.IOBluetoothFamily	9.0.0
    com.apple.driver.FairPlayIOKit	68.13.1
    com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
    com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
    com.apple.driver.AppleSSE	1.0
    com.apple.driver.AppleSEPKeyStore	2
    com.apple.driver.AppleUSBTDM	532.40.7
    com.apple.iokit.IOUSBMassStorageDriver	209.40.6
    com.apple.iokit.IOPCIFamily	2.9
    com.apple.iokit.IOSCSIBlockCommandsDevice	452.60.2
    com.apple.iokit.IOSCSIArchitectureModelFamily	452.60.2
    com.apple.driver.AppleIPAppender	1.0
    com.apple.driver.AppleFDEKeyStore	28.30
    com.apple.driver.AppleEffaceableStorage	1.0
    com.apple.driver.AppleCredentialManager	1.0
    com.apple.driver.KernelRelayHost	1
    com.apple.iokit.IOUSBHostFamily	1.2
    com.apple.driver.AppleUSBHostMergeProperties	1.2
    com.apple.driver.usb.AppleUSBCommon	1.0
    com.apple.driver.AppleSMC	3.1.9
    com.apple.driver.RTBuddy	1.0.0
    com.apple.driver.AppleEmbeddedTempSensor	1.0.0
    com.apple.driver.AppleARMPMU	1.0
    com.apple.iokit.IOAccessoryManager	1.0.0
    com.apple.driver.AppleOnboardSerial	1.0
    com.apple.iokit.IOSkywalkFamily	1.0
    com.apple.driver.mDNSOffloadUserClient	1.0.1b8
    com.apple.iokit.IONetworkingFamily	3.4
    com.apple.iokit.IOSerialFamily	11
    com.apple.driver.AppleSEPManager	1.0.1
    com.apple.driver.AppleA7IOP	1.0.2
    com.apple.driver.IOSlaveProcessor	1
    com.apple.driver.AppleBiometricSensor	2
    com.apple.iokit.IOHIDFamily	2.0.0
    com.apple.iokit.CoreAnalyticsFamily	1
    com.apple.driver.AppleANELoadBalancer	5.35.2
    com.apple.driver.AppleH11ANEInterface	5.35.0
    com.apple.AUC	1.0
    com.apple.iokit.IOAVFamily	1.0.0
    com.apple.iokit.IOHDCPFamily	1.0.0
    com.apple.iokit.IOCECFamily	1
    com.apple.iokit.IOAudio2Family	1.0
    com.apple.driver.AppleIISController	100.1
    com.apple.driver.AppleAudioClockLibs	100.9.1
    com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
    com.apple.iokit.IOSurface	302.11.1
    com.apple.driver.IODARTFamily	1
    com.apple.security.quarantine	4
    com.apple.security.sandbox	300.0
    com.apple.kext.AppleMatch	1.0.0d1
    com.apple.driver.AppleMobileFileIntegrity	1.0.5
    com.apple.security.AppleImage4	4.2.0
    com.apple.kext.CoreTrust	1
    com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
    com.apple.driver.AppleARMPlatform	1.0.2
    com.apple.iokit.IOStorageFamily	2.1
    com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
    com.apple.iokit.IOReportFamily	47
    com.apple.kec.pthread	1
    com.apple.kec.Libm	1
    com.apple.kec.corecrypto	12.0
    
    
    
    ** Stackshot Succeeded ** Bytes Traced 450326 (Uncompressed 1236352) **

**Comment by Ste-SR** [comment]
Here is also the !gddiagnostic output

### Workflow version
2022.7

### Alfred version
4.6.3

### macOS version
12.2.1

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive
}

### Google drive paths
Exists: /Volumes/GoogleDrive
712M
331598 paths

### Cache dir
cache.db
tmp.db

### Cache file
16777230 12228782 -rw-r--r-- 1 username staff 0 5300224 "Feb 22 10:57:10 2022" "Feb 21 23:11:22 2022" "Feb 21 23:11:22 2022" "Feb 21 20:00:04 2022" 4096 10360 0 /Users/username/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
16777230 12662092 -rw-r--r-- 1 username staff 0 35229696 "Feb 23 20:17:17 2022" "Feb 23 20:17:17 2022" "Feb 23 20:17:17 2022" "Feb 23 20:00:04 2022" 4096 69760 0 /Users/username/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/tmp.db

### Build progress
NOT running

### Launchd job
Loaded: -	1	com.alfredapp.launchd.googledrivecache
Installed

**Comment by vitorgalvao** [comment]
> Now that it has become a default setting for this plugin, I fear this may result in many confused users finding out every morning that their Mac has crashed overnight.

I thank you for the concern and attention, but that is unlikely.

I made Shared Drives the default partly because people keep asking how to do it. None has reported kernel panics after setting it up.

The most likely culprit is Google Drive. I find several reports of it causing kernel panics for other reasons. But if the cause of the panic is something the Workflow can trigger, finding what that is would be useful to go around it and/or report it to Google. Unfortunately, I don’t recognise anything useful in that log.

I’ll close since this isn’t widespread and the current info doesn’t give us a clue. May be something in particular with your setup. If it becomes more common, we’ll have more data.

That said, I’m currently investigating another situation whose fix may end up working for this too. [Give it a try if you want](https://github.com/alfredapp/google-drive-workflow/files/8137071/Google.Drive.alfredworkflow.zip).

Thank you again.

**Comment by vitorgalvao** [comment]
@Ste-SR Could you share the full paths to your drives?
