### ISSUE TITLE
On Startup - Alfred Launches Before Google Drive

### ISSUE THREAD

**Issue by vanduse1** [alfredapp/google-drive-workflow#29]
When I start my computer, Alfred is launching before Google Drive is completed. 

I get an error on startup as the Google Drive isn't available when the script (I assume index) tries to launch. Is there anything I can do to introduce a delay in the index rebuild? Other ideas?

**Comment by vitorgalvao** [comment]
> I get an error on startup

Can I get a screenshot?

**Comment by vanduse1** [comment]
![Screen Shot 2022-02-24 at 10 44 41 AM](https://user-images.githubusercontent.com/6863381/155579264-234cb592-fea7-4d61-ac17-93d8309a6828.png)

See attached. Just a simple message that the drive path is not available. If I force a reindex after Google Drive finishes loading, it works without issue.

**Comment by vitorgalvao** [comment]
Note the index rebuilds on startup and every day at 20:00 (so it works both for people who reboot frequently and those who do so rarely), so might still be getting it updated.

Still, I agree seeing the notification itself is annoying.

Try this one [Google Drive.alfredworkflow.zip](https://github.com/alfredapp/google-drive-workflow/files/8134962/Google.Drive.alfredworkflow.zip). If you still get the error, edit this object (highlighted in the centre):

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1699443/155587104-fcc1d681-323e-4cd9-ae84-26d0982e5bdb.png">

Increase the number until it works. Report back the lowest number which works consistently, and I’ll integrate it into the Workflow.

**Comment by vanduse1** [comment]
I have tried 2 times now. 5 seconds wasn't long enough but 10 seemed to work. I will update if I see any issues with 10 going forward. I don't reboot that often but will try a time or two over the next few days. 
Thanks for such a quick response!

**Comment by vitorgalvao** [comment]
> I will update if I see any issues with 10 going forward. I don't reboot that often but will try a time or two over the next few days.

Thank you. I’d like to make a new release over or after the weekend, since there’s another fix I’m testing which I’d like to fit in as well.

**Comment by vanduse1** [comment]
So far so good with my delay number at 10.

**Comment by vitorgalvao** [comment]
Thank you for the followup. I’ll make the release today.
