### ISSUE TITLE
Workflow help

### ISSUE THREAD

**Issue by vendetta677** [alfredapp/google-drive-workflow#34]
### Workflow version
2022.10

### Alfred version
4.6.5

### macOS version
12.2.1

### Architecture
arm64

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    auto_refresh = 1
    google_drive_path = /Volumes/GoogleDrive
}

### Full Disk Access
Granted

### Google drive paths
Does NOT Exist: /Volumes/GoogleDrive

### Cache dir
cache.db

### Cache file
16777230 19613027 -rw-r--r-- 1 joshberris staff 0 2183168 "Apr  7 10:38:01 2022" "Apr  6 20:04:16 2022" "Apr  6 20:04:16 2022" "Apr  6 20:00:59 2022" 4096 6208 0 /Users/joshberris/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
NOT loaded
NOT installed

### Debugger output

```codeblock
[10:09:55.951] Google Drive[Script Filter] Processing complete
[10:09:55.953] Google Drive[Script Filter] Passing output '/Volumes/GoogleDrive/My Drive/My Clients/Archive' to Conditional
[10:09:55.954] Google Drive[Conditional] Processing complete
[10:09:55.955] Google Drive[Conditional] Passing output '/Volumes/GoogleDrive/My Drive/My Clients/Archive' to Open File
```

### More details

Doesn't open google drive files anymore. When I click it, nothing happens. Typically amazing workflow! Thank you for creating!

<img width="567" alt="Screen Shot 2022-04-30 at 10 06 09 AM" src="https://user-images.githubusercontent.com/102245304/166115331-bfd98a83-6743-458b-9428-4249d43d4c20.png">

**Comment by vitorgalvao** [comment]
> Does NOT Exist: /Volumes/GoogleDrive

Something happened with your Google Drive. Perhaps Google changed its location. [Confirm the path](https://www.howtogeek.com/721126/3-ways-to-see-the-current-folder-path-on-mac/).

**Comment by vendetta677** [comment]
Fixed thank you!
