### ISSUE TITLE
Search subfolder

### ISSUE THREAD

**Issue by petervangalen** [alfredapp/google-drive-workflow#4]
Hi, this is great, thanks for developing!
Is there an easy way to set up a keyword to search only one subfolder within Google Drive?
Peter

**Comment by vitorgalvao** [comment]
> Is there an easy way to set up a keyword to search only one subfolder within Google Drive?

Change the `google_drive_path` environment variable, [as per the instructions](https://github.com/alfredapp/google-drive-workflow#instructions).

Unless you mean *adding* a keyword that will only search one directory while keeping the main one to search everything. In that case, no, it’s not easily possible and it would complicate the interface for everyone else, so I consider it out of scope for this Workflow.
