### ISSUE TITLE
How to create a keyboard shortcut for the Google Drive Workflow

### ISSUE THREAD

**Issue by lemikeone** [alfredapp/google-drive-workflow#40]
Thanks for making this great workflow, very useful!

I was wondering : how can I create a keyboard shortcut to launch this workflow instead of having to write "gd" every time? If I create it directly in the workflow, it will be erased every time the workflow is updated, isn't it?

Thanks!

**Comment by vitorgalvao** [comment]
A simple way of doing it is making a new Workflow and connecting a Hotkey to a Show Alfred Utility with the Keyword.

But [here’s a version with Hotkeys](https://github.com/alfredapp/google-drive-workflow/files/9042962/Google.Drive.alfredworkflow.zip). Adding them to the next release with other improvements.

**Comment by lemikeone** [comment]
Thanks!
