### ISSUE TITLE
Finding files in "Linked Shared Folders" in latest version 59

### ISSUE THREAD

**Issue by mschel** [alfredapp/google-drive-workflow#41]
### Workflow version
2022.12

### Alfred version
4.6.7

### macOS version
12.4

### Architecture
i386

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    auto_refresh = 1
    google_drive_path = /Volumes/GoogleDrive
}

### Full Disk Access
Granted

### Google drive paths
Exists: /Volumes/GoogleDrive
7094 paths

### Cache dir
cache.db

### Cache file
16777221 101506065 -rw-r--r-- 1 xxx staff 0 8192 "Jun 30 09:49:12 2022" "Jun 30 09:48:27 2022" "Jun 30 09:48:27 2022" "Jun 30 09:48:27 2022" 4096 16 0 /Users/xxx/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.googledrive
Installed

### Debugger output

```codeblock
No Output of failing
```

### More details

Hi there,

before the latest Update to 59.0.3 the workflow was fine finding files in Streaming Mode. Even in any linked shared Folder.
Now - as the option to enable Spotlight in GD Client - the workflow only finds files stored directly (no symlinks, but streamed) in my folder.

The search inside the GD Client still finds everything.

No difference between Spotligh support being turned on/off.

Examples:

Found: /Volumes/GoogleDrive/Test.pdf
Not found (anymore): /Volumes/GoogleDrive/.shortcut-targets-by-id/1XwT7xEzeWDw9nGnz1_lWkJxAI7dlClJQ/Test.pdf

Cheers
Marcel

**Comment by vitorgalvao** [comment]
A likely candidate for the problem is that Google made changes to your drive before the Workflow’s cache has had the chance to rebuild. Force it with `:gdrebuildcache` and wait for the notification, then try again.

**Comment by mschel** [comment]
Ah well - did this like 10 times in the morning and even deleted all the cache files manually but it didn't work. But now it's all there again after rebuilding the cache. Strange but seems like it's no problem at all with the new Spotligh feature of the client 👍
