### ISSUE TITLE
Drive search scope includes unwanted .Encrypted volume

### ISSUE THREAD

**Issue by joeljean** [alfredapp/google-drive-workflow#45]
Thanks for this great tool. It used to work smoothly, but I've noticed in the past few weeks that Drive search results now include 2 versions of all files/folders, one at the expected location of /Volumes/GoogleDrive/MyDrive/... and one on an apparently hidden encrypted volume at /Volumes/GoogleDrive/.Encrypted/My Drive/... Accidentally opening the latter encrypted folder and adding any file seems to kill Drive syncing indefinitely—requiring deletion of the entire DriveFS cache in Library every time and restarting syncing from scratch. The cost of this failure mode is super high and kills usability.

Is there any way to restrict indexing/search scope to avoid the .Encrypted volume? Thanks!

**Comment by vitorgalvao** [comment]
Add `.Encrypted` to the Ignore List configuration.

For future reports, please don't skip the template. The diagnostic takes but a second to get and might’ve shown alternative solutions.
