### ISSUE TITLE
"Google Drive path does not exist!"

### ISSUE THREAD

**Issue by wuesten-fuchs** [alfredapp/google-drive-workflow#48]
### Workflow version
2022.16

### Alfred version
5.0.1

### macOS version
12.5

### Architecture
arm64

### Preferences
Default

### Full Disk Access
Granted

### Google drive path
Does NOT Exist: /Volumes/GoogleDrive

### Cache dir
cache.db

### Cache file
16777229 43729281 -rw-r--r-- 1 florianschmitt staff 0 8192 "Aug 11 14:53:30 2022" "Aug 11 14:53:27 2022" "Aug 11 14:53:27 2022" "Aug 11 14:53:27 2022" 4096 16 0 /Users/florianschmitt/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.googledrive
Installed

### Debugger output

```codeblock
[15:11:54.089] Logging Started...
[15:11:57.763] Google Drive[Script Filter] Queuing argument 'b'
[15:11:57.955] Google Drive[Script Filter] Script with argv 'b' finished
[15:11:57.958] Google Drive[Script Filter] {"items":[{"title":"Nothing found","subtitle":"Try searching something else"}]}
```

### More details

I just installed the workflow.
At that point I had the Google Drive Mac app set to 
**Mirror files**

- Store all My Drive files in the cloud and on your computer
- Access files from a folder on your computer
- All files are automatically available offline

At that point, the folder path was  
/Users/myusername/Google Drive

And I got the following error message from the workflow:
_Google Drive path does not exist!_

Then I changed the Google Drive setting to 
**Stream files**

- Store all My Drive files in the cloud only
- Access files from a virtual drive or folder on your computer
- Choose specific files and folders to make available offline.

The folder was moved to 
/Users/myusername/Library/CloudStorage/GoogleDrive-my-email-address@gmail.com/My Drive

Still, the same error message.

What am I doing wrong here?
I feel like I have a standard Google Drive setup.

**Comment by vitorgalvao** [comment]
Thank you for the thorough report, it makes debugging easier and I can help you faster. The clue is in the diagnostic:

> Does NOT Exist: /Volumes/GoogleDrive

If you don’t have Google Drive at that location, you need to change it. Open the Workflow in the editor and click `Configure Workflow` on the top left. This is also visible when you first install it.

> I feel like I have a standard Google Drive setup.

At this point that doesn’t exist. Google is slowly changing people’s Google Drive location so different people have it in different places. It’s unclear how far ahead they are in the transition.

**Comment by wuesten-fuchs** [comment]
Ok, works like a charm.
Should have had a closer look.

Thank you!
