### ISSUE TITLE
The use of Umlauts (ä, ö, ü) leads to an empty result

### ISSUE THREAD

**Issue by wuesten-fuchs** [alfredapp/google-drive-workflow#49]
### Workflow version
2022.16

### Alfred version
5.0.1

### macOS version
12.5

### Architecture
arm64

### Preferences
Dict {
    google_drive_path = /Users/XXX/Library/CloudStorage/GoogleDrive-f.schmitt94@gmail.com/My Drive/vegconomist
}

### Full Disk Access
Granted

### Google drive path
Exists: /Users/XXX/Library/CloudStorage/GoogleDrive-f.schmitt94@gmail.com/My Drive/vegconomist
14978 paths

### Cache dir
cache.db

### Cache file
16777229 43875947 -rw-r--r-- 1 XXX staff 0 3641344 "Aug 12 11:44:21 2022" "Aug 12 11:44:01 2022" "Aug 12 11:44:01 2022" "Aug 12 11:37:04 2022" 4096 8320 0 /Users/XXX/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.googledrive
Installed

### Debugger output

```codeblock
[11:53:37.844] Logging Started...
[11:53:41.440] Google Drive[Script Filter] Queuing argument 'ö'
[11:53:41.647] Google Drive[Script Filter] Script with argv 'ö' finished
[11:53:41.650] Google Drive[Script Filter] {"items":[{"title":"Nothing found","subtitle":"Try searching something else"}]}
```

### More details

When I search "gd ö" or any other umlaut I get an empty result although I definitely have files in my Google Drive with those characters.

**Comment by vitorgalvao** [comment]
Looks like a previous fix is no longer necessary. Should be working in [2022.17](https://github.com/alfredapp/google-drive-workflow/releases/tag/2022.17). Don’t forget to `:gdrebuildcache` before trying.

**Comment by wuesten-fuchs** [comment]
Works like a charm 👌 Thank you!

**Comment by matkovsky** [comment]
Well, simple diacritics are now breaking the search for me in version 2022.17, after freshly rebuilt cache. See examples:

![CleanShot 2022-08-18 at 13 58 05](https://user-images.githubusercontent.com/1693178/185389635-4f733438-2cdc-4162-bd1a-72ea3f3c7006.png)

![CleanShot 2022-08-18 at 13 58 14](https://user-images.githubusercontent.com/1693178/185389641-76ed06bf-a6e0-40f7-a98b-90450215c004.png)

_(„Bevételeim” means „My incomes” in Hungarian 🙈 😆)_

**Comment by vitorgalvao** [comment]
@matkovsky @Ben9000 Can you both check if [this one](https://github.com/alfredapp/google-drive-workflow/files/9373671/Google.Drive.alfredworkflow.zip) works for you? Don’t forget to `:gdrebuildcache`.

**Comment by wuesten-fuchs** [comment]
Yes, the Umlaut (ä, ö, ü) now work for me as expected.

**Comment by matkovsky** [comment]
@vitorgalvao Oh, yes, it works! Thank you! 🙏 😎

![CleanShot 2022-08-24 at 13 48 25](https://user-images.githubusercontent.com/1693178/186411066-1cff5f6e-17d1-4688-9bdc-f0f628d629a1.png)

**Comment by vitorgalvao** [comment]
Thank you for the replies. Change live in [2022.18](https://github.com/alfredapp/google-drive-workflow/releases/tag/2022.18). It’s identical to the one posted above, except for the version bump.
