### ISSUE TITLE
Enhancement: Fallback result option

### ISSUE THREAD

**Issue by mrtraced** [alfredapp/google-drive-workflow#50]
Add a Fallback Search box saying  _Search Google Drive for '{query]'_. Fallback result means we don't have to manually trigger the workflow separately. I add this manually after every update. Thanks for making such a solid workflow Vitor!

**Comment by vitorgalvao** [comment]
Thank you for the kinds words. And I like the idea! It’s now in [2022.19](https://github.com/alfredapp/google-drive-workflow/releases/tag/2022.19).
