### ISSUE TITLE
Enhancement: remove the drive path from the subtitle

### ISSUE THREAD

**Issue by ajimix** [alfredapp/google-drive-workflow#51]
Would be great to be able to remove all this prefix (red underline) which is the same for all results (as it's the google drive path) and takes precious space from the results, so it makes it impossible to see the actual path.

![2022-09-19 at 15 45 34@2x](https://user-images.githubusercontent.com/30565/190971860-36b9ba55-8cd4-431e-ae08-900565daafd0.png)

**Comment by vitorgalvao** [comment]
The red line is covering too much. Plenty of people have several Google Drive paths at once, so that prefix is meaningful. But I’ve made it shorter in [2022.21](https://github.com/alfredapp/google-drive-workflow/releases/tag/2022.21).
