### ISSUE TITLE
gdf works, gd doesn't, shows normal, system-wide search results

### ISSUE THREAD

**Issue by wuesten-fuchs** [alfredapp/google-drive-workflow#52]
### Workflow version
2022.20

### Alfred version
5.0.2

### macOS version
12.5

### Architecture
arm64

### Preferences
Dict {
    google_drive_path = /Users/florianschmitt/My Drive (f.schmitt94@gmail.com)/vegconomist neu
}

### Full Disk Access
Granted

### Google drive path
Exists: /Users/florianschmitt/My Drive (f.schmitt94@gmail.com)/vegconomist neu
12146 paths

### Cache dir
cache.db

### Cache file
16777234 50434396 -rw-r--r-- 1 florianschmitt staff 0 2203648 "Sep 20 11:54:39 2022" "Sep 20 11:54:25 2022" "Sep 20 11:54:25 2022" "Sep 20 11:54:22 2022" 4096 6208 0 /Users/florianschmitt/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.googledrive
Installed

### Debugger output

```codeblock
[11:57:23.998] Logging Started...
[11:57:26.488] Google Drive[Script Filter] Queuing argument 't'
[11:57:26.522] Google Drive[Script Filter] Queuing argument 'te'
[11:57:26.683] Google Drive[Script Filter] Script with argv 'te' finished
[11:57:26.686] Google Drive[Script Filter] {"items":[{"uid":"/Users/florianschmitt/My Drive (mygmailaddress@gmail.com)/**********
```

### More details

My Google Drive Path:
/Users/myname/My Drive (xyz@gmail.com)/ASubFolder

I can search for folders just fine (with gdf) but when I enter gd and then try to search, I get system-wide search results.

Could it be because I mirror and don't stream my files through Google Drive? Streaming has other issues for me. After each restart I need to configure it again.a

**Comment by vitorgalvao** [comment]
Not sure why you’re seeing system-wide results, that sounds like you might have an external fallback or something else.

But as to the larger cause, [2022.21](https://github.com/alfredapp/google-drive-workflow/releases/tag/2022.21) is likely to fix it.
