### ISSUE TITLE
Google drive actions don't include "open" (treating it as text?)

### ISSUE THREAD

**Issue by jheathco** [alfredapp/google-drive-workflow#53]
Not sure what's happened, but this started occurring with v4 and has continued after an upgrade to v5.

Please see:

<img width="765" alt="1" src="https://user-images.githubusercontent.com/96809/195717023-d640c0ec-ee16-48c6-a117-4af4b3949f0e.png">

**Comment by vitorgalvao** [comment]
Probably what happened is that Google updated your Drive location. You have to fix that in the configuration. The [second post on the forum](https://www.alfredforum.com/topic/17318-google-drive-—-list-file-stream-contents-from-google-drive/#comment-89267) tells you how to find the path. Don’t forget to run `:gdrebuildcache` afterwards.

Next time, please don’t skip the template. I can’t properly investigate without the requested information.

If the above doesn’t fix your issue, run `!gddiagnostic`.
