### ISSUE TITLE
Google Drive Workflow

### ISSUE THREAD

**Issue by Koenraad63** [alfredapp/google-drive-workflow#59]
For some reason, the Google Drive and Google Folder workflows do not work at all for me. No initial cache building takes place.

**Comment by vitorgalvao** [comment]
Please do not skip the issue template. It is impossible to know what the problem might be without the required information. Run `!gddiagnostic` in Alfred.

**Comment by Koenraad63** [comment]
### Workflow version
2022.24

### Alfred version
5.0.6

### macOS version
13.1

### Architecture
arm64

### Preferences
Default

### Full Disk Access
Granted

### Google drive path
Does NOT Exist: /Volumes/GoogleDrive

### Cache dir
Files NOT present

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.vitor.googledrive
Installed

**Comment by vitorgalvao** [comment]
> Does NOT Exist: /Volumes/GoogleDrive

Your Google Drive folder is not set correctly. Google probably updated you to the new version which changes its location. You’ll need to update it in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) for changes to continue to be detected.
 
If you don’t know how to find where your Google Drive is, [How-To Geek has the steps](https://www.howtogeek.com/721126/3-ways-to-see-the-current-folder-path-on-mac/).
