### ISSUE TITLE
No google drive path?

### ISSUE THREAD

**Issue by cgrattonUW** [alfredapp/google-drive-workflow#60]
Hi folks - 

I know this is a recurring issue and I have tried to follow the suggestions to others. Google seems to have moved something and the workflow can't find my files or rebuild a cache.  I can't seem to figure out how to get this to work.

Here is the initial error:

### Workflow version
2022.23

### Alfred version
5.0.6

### macOS version
13.1

### Architecture
arm64

### Preferences
Default

### Full Disk Access
Granted

### Google drive path
Does NOT Exist: /Volumes/GoogleDrive

### Cache dir
cache.db

### Cache file
16777233 46325452 -rw-r--r-- 1 myusername staff 0 9748480 "Dec 17 18:32:05 2022" "Dec 17 18:32:05 2022" "Dec 17 18:32:05 2022" "Dec 17 18:13:23 2022" 4096 20496 0 /Users/myusername/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.vitor.googledrive
Installed

--------

As far as I can tell, this is now under  /Users/myusername/Library/CloudStorage/GoogleDrive

When I put this in the config, it gives this error:

### Workflow version
2022.23

### Alfred version
5.0.6

### macOS version
13.1

### Architecture
arm64

### Preferences
Dict {
    google_drive_path = /Users/myusername/Library/CloudStorage/GoogleDrive
}

### Full Disk Access
Granted

### Google drive path
Does NOT Exist: /Users/myusername/Library/CloudStorage/GoogleDrive

### Cache dir
cache.db

### Cache file
16777233 46325452 -rw-r--r-- 1 myusername staff 0 9748480 "Dec 17 18:32:05 2022" "Dec 17 18:32:05 2022" "Dec 17 18:32:05 2022" "Dec 17 18:13:23 2022" 4096 20496 0 /Users/myusername/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.vitor.googledrive
Installed
----------

Any help would be appreciated.

**Comment by vitorgalvao** [comment]
> As far as I can tell, this is now under /Users/myusername/Library/CloudStorage/GoogleDrive

It will be something more specific, like `GoogleDrive-othertexthere`.

In the Workflow’s configuration you can click the folder icon and navigate to the Google Drive location from there.

Or navigate to it in the Finder and [get it there](https://www.howtogeek.com/721126/3-ways-to-see-the-current-folder-path-on-mac/).
