### ISSUE TITLE
Diagnostic cache path broken

### ISSUE THREAD

**Issue by dmangin** [alfredapp/google-drive-workflow#61]
### Workflow version
2023.3

### Alfred version
5.0.6

### macOS version
13.1

### Architecture
arm64

### Preferences
Dict {
    auto_refresh = false
    google_drive_path = /Users/XXXX/Library/CloudStorage/GoogleDrive-XXXX
    search_keyword = ''
    result_limit = 50
    ignore_list = .Encrypted/
}

### Full Disk Access
Granted

### Google drive path
Exists: /Users/XXXX/Library/CloudStorage/GoogleDrive-XXXX
23109 paths

### Cache dir
Files NOT present

### Cache file
Does NOT exist

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
NOT loaded
NOT installed

### Debugger output

```codeblock
N/A
```

### More details

Hi in a recent (2023.3 ?) version, you changed the bundle ID from `com.alfredapp.googledrive` to `com.alfredapp.vitor.googledrive`

Therefore, I think the `!gddiagnostics` script line 
`readonly cache_dir="${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive"
`
should be updated to
`readonly cache_dir="${HOME}/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.vitor.googledrive"`
to be functional again.

With the current version, the diagnostic always says that cache file does not exist :)

**Comment by vitorgalvao** [comment]
Indeed. It should be `alfred_workflow_cache`, really. That’s probably a remnant of early tests.

Thank you for the report. I’ll make a release soon with the correction.
