### ISSUE TITLE
ability to create new documents

### ISSUE THREAD

**Issue by akaBigCat** [alfredapp/google-drive-workflow#64]
### Feature details

One nice feature from azai91 was the ability to create a new document (doc, sheet, etc) right from alfred.
https://github.com/azai91/alfred-drive-workflow?tab=readme-ov-file#commands
Would be great to have this functionality as well

**Comment by vitorgalvao** [comment]
Thank you for the request, but that is out of scope. That would require using the Google Drive API, which adds a lot of complexity (and be at the mercy of Google’s ever changing whims) for a feature which hasn’t been requested in all these years. Complexity not only of code, but maintenance and user setup.

The goal of this workflow is explicitly to bridge the gap with the missing Spotlight indexing, and it should be considered feature complete. Eventual bugs would still be fixed, naturally, but this has been very stable for a long while.
